name: Impact Analysis Report

on:
  push:
    branches:
      - master

jobs:
  impact-analysis-report:
    name: Impact Analysis Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures we have at least two commits

      - name: Get Changed Java Files
        id: changed-files
        run: |
          git fetch --all

          # Check if we have at least two commits
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- '*.java' || true)
          else
            echo "Only one commit found, skipping diff check."
            CHANGED_FILES=""
          fi

          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "::set-output name=changed::$CHANGED_FILES"
        shell: bash

      - name: Display Changed Java Files
        run: echo "$CHANGED_FILES"
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install openai==0.28

      - name: Check if Code Changes Exist
        id: check-changes
        run: |
          if [[ -z "${{ steps.changed-files.outputs.changed }}" ]]; then
            echo "NO_CODE_CHANGES=true" >> $GITHUB_ENV
          else
            echo "NO_CODE_CHANGES=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run Code Analysis (If Changes Exist)
        if: env.NO_CODE_CHANGES == 'false'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python analyze_changes.py "${{ steps.changed-files.outputs.changed }}"
        shell: bash

      - name: Generate No Changes Report
        if: env.NO_CODE_CHANGES == 'true'
        run: |
          TIMESTAMP=$(TZ="Asia/Kolkata" date '+%Y-%m-%d %H:%M:%S')
          echo "No code changes detected as of $TIMESTAMP" > impact_analysis_report.txt
        shell: bash

      - name: Ensure Report File Exists
        run: |
          if [ ! -f impact_analysis_report.txt ]; then
            echo "No code changes detected" > impact_analysis_report.txt
          fi
        shell: bash

      - name: Convert Report to HTML
        run: |
          TIMESTAMP=$(TZ="Asia/Kolkata" date '+%Y-%m-%d %H:%M:%S')
          echo "<html><head><title>Impact Analysis Report</title><style>body{font-family:sans-serif;padding:20px;}</style></head><body><h1>Impact Analysis Report</h1><p>Generated on $TIMESTAMP (IST)</p><pre>" > index.html
          cat impact_analysis_report.txt >> index.html
          echo "</pre></body></html>" >> index.html
        shell: bash

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: impact-analysis-html
          path: index.html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan gh-pages
          git reset
          git add index.html
          git commit -m "Deploy Impact Analysis Report"
          git push --force origin gh-pages
        shell: bash
