name: Impact Analysis Report

on:
  push:
    branches:
      - master

jobs:
  impact-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # Ensures we have at least one previous commit for comparison

    - name: Get Changed Java Files
      id: changed-files
      run: |
        git fetch --all
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.java$')
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Display Changed Java Files
      run: echo "$CHANGED_FILES"

    - name: Save Changed Files to Artifact
      run: echo "$CHANGED_FILES" > changed_files.txt
      shell: bash

    - name: Upload Impact Analysis Report
      uses: actions/upload-artifact@v4
      with:
        name: impact-analysis-report
        path: changed_files.txt

    # Uncomment and update these steps as needed
    # - name: SonarQube Analysis
    #   run: mvn sonar:sonar -Dsonar.projectKey=my-java-app -Dsonar.organization=my-org

    # - name: Run JArchitect
    #   run: JArchitectConsole.exe MyJavaProject.jar /DependencyGraph > impact_report.txt

    # - name: Upload Impact Report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: impact-report
    #     path: impact_report.txt