name: Impact Analysis Report

on:
  push:
    branches:
      - master

jobs:
  impact-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # Ensures we have at least one previous commit for comparison

    - name: Get Changed Java Files
      id: changed-files
      run: |
        git fetch --all
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.java$')
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Analyze Code Changes
      run: |
        python analyze_changes.py "$CHANGED_FILES"

    - name: Upload Impact Analysis Report
      uses: actions/upload-artifact@v4
      with:
        name: impact-analysis-report
        path: impact_analysis_report.txt