name: Impact Analysis Report

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get Changed Java Files
        id: changed-files
        run: |
          git fetch --all
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.java$' || true)
          echo "changed=$CHANGED_FILES" >> $GITHUB_ENV
          echo "::set-output name=changed::$CHANGED_FILES"
        shell: bash

      - name: Display Changed Java Files
        run: echo "$CHANGED_FILES"
        shell: bash

  impact-analysis:
    name: Analyze Impact of Changes
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      analysis_done: ${{ steps.analysis.outputs.done }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install openai==0.28

      - name: Check if Code Changes Exist
        id: check-changes
        run: |
          if [[ -z "${{ needs.setup.outputs.changed_files }}" ]]; then
            echo "NO_CODE_CHANGES=true" >> $GITHUB_ENV
          else
            echo "NO_CODE_CHANGES=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run Code Analysis (If Changes Exist)
        if: env.NO_CODE_CHANGES == 'false'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python analyze_changes.py "${{ needs.setup.outputs.changed_files }}"
        shell: bash

      - name: Generate No Changes Report
        if: env.NO_CODE_CHANGES == 'true'
        run: |
          echo "No code changes detected" > impact_analysis_report.txt
        shell: bash

  generate-report:
    name: Generate HTML Report
    needs: impact-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure Report File Exists
        run: |
          if [ ! -f impact_analysis_report.txt ]; then
            echo "No code changes detected" > impact_analysis_report.txt
          fi
        shell: bash

      - name: Convert Report to HTML
        run: |
          echo "<html><head><title>Impact Analysis Report</title></head><body><pre>" > index.html
          cat impact_analysis_report.txt >> index.html
          echo "</pre></body></html>" >> index.html
        shell: bash

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: impact-analysis-html
          path: index.html

  deploy:
    name: Deploy to GitHub Pages
    needs: generate-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: impact-analysis-html

      - name: Push to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan gh-pages
          git reset
          git add index.html
          git commit -m "Deploy Impact Analysis Report"
          git push --force origin gh-pages
        shell: bash
